# Alacritty Configuration

[general]
import = ["./colors.toml"]

[window]
padding.x = 10
padding.y = 10
dynamic_padding = true
opacity = 0.9
decorations = "none"

[font]
size = 12

# NOTE: alacritty doesn't support ligatures, just using this since it's my preferred font with nerdfonts.
[font.normal]
family = "Liga SFMono Nerd Font"

[scrolling]
multiplier = 6

[selection]
save_to_clipboard = true

[cursor]
style.shape = "Block"
unfocused_hollow = true

[mouse]
hide_when_typing = true
